// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4Dg5qpT0OwEWmq2DphfO0yOL9zfS8rU',
    appId: '1:514327652972:web:3fe2fb61d58f2c50af4649',
    messagingSenderId: '514327652972',
    projectId: 'v-cec-7b97c',
    authDomain: 'v-cec-7b97c.firebaseapp.com',
    storageBucket: 'v-cec-7b97c.appspot.com',
    measurementId: 'G-8ZCZW7WCXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJ4Ao-VtnHd7aiJLLJyjHYF1C6Wiq1P0',
    appId: '1:514327652972:android:f528ad9da7404beaaf4649',
    messagingSenderId: '514327652972',
    projectId: 'v-cec-7b97c',
    storageBucket: 'v-cec-7b97c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhN3eaI8X5C7yFPXncRU9vmdPRWQmtKo',
    appId: '1:514327652972:ios:7283ce723bb7aaebaf4649',
    messagingSenderId: '514327652972',
    projectId: 'v-cec-7b97c',
    storageBucket: 'v-cec-7b97c.appspot.com',
    iosClientId: '514327652972-9lspu01a3ld5meu7j9i9h36nl0h2r48t.apps.googleusercontent.com',
    iosBundleId: 'com.example.vCec2',
  );
}
